###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

############################
# --- Required options --- #
############################

title: My Training report
author: "Ansh Tyagi (URN: 2302857)"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "index"
  Blog:
    - Day 1: "day1"
    - Day 2: "day2"
    - Day 3: "day3"
    - Day 4: "day4"
  About Me: "about"

################
# --- Logo --- #
################

round-avatar: true
#title-img: /assets/img/logo.png

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "anshtuffy47@gmail.com"
  rss: true
  github: anshtyagi-47
  linkedin: Ansh Tyagi

rss-description: my training blogs

###########################
# --- General options --- #
###########################

share-links-active:
  linkedin: true

url-pretty: "https://tyagitraining.com"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

#mobile-theme-col: "#0085A1"

#site-css:
#  - "/assets/css/custom-styles.css"

#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""
#gtm: ""

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

#google_analytics: "UA-XXXXXXXX-X"

####################
# --- Comments --- #
####################

#disqus: ""
#fb_comment_id: ""
#commentbox: ""
#utterances:
#  repository: 
#  issue-term: title
#  theme: github-light
#  label: blog-comments

#staticman:
#  repository : 
#  branch     : master
#  endpoint   : 
#  reCaptcha:
#    siteKey  : 
#    secret   : 

#giscus:
#  hostname: giscus.app
#  repository: 
#  repository-id: 
#  category: Announcements
#  category-id: 
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"

#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
